### ISSUE TITLE
Raspberry CPU al 100%

### ISSUE THREAD

**Issue by cent89** [mrf345/FQM#103]
Hi, thanks for your project!
I've installed FQM on Raspberry PI 3+, running in cli mode with:

`python3 run.py --cli --ip 192.168.7.100 --port 3790 --quiet`

It works well but I have two problems:
1) While a display screen is opened, the whole system is too slow; python use the 90-100% of CPU! It's normal? There are some min requirements?

2) I've installed a POS printer, and the test page from CUPS is ok. But in FQM, after a button service is pressed, the page loops forever, even if the python process uses 2-3% of CPU. Where is the problem?

Thanks!
Roberto

**Comment by mrf345** [comment]
Hello, thanks for the well detailed issue!

Last time i remember testing it with Raspberry PI, probably two years ago. It wasn't perfect, but i don't remember the CPU throttling at all 🤔

Perhaps it's an ARM devices bug, did you checkout the `errors.log` file content ? and could you please attach it here. Regarding the printing issue that sounds like a bug, it should have logged something in `project_folder/errors.log`.

My pleasure, all the best.

**Comment by mrf345** [comment]
Unfortunately i won't have enough time to reproduce it locally. if someone else wants to give a try https://azeria-labs.com/emulate-raspberry-pi-with-qemu/

**Comment by mrf345** [comment]
I took another look today and was able to reproduce it. Turns out a front-end interval was emitting too many requests to the back-end.

I'm about to merge some refactoring https://github.com/mrf345/FQM/pull/132 to reduce them. And now you should be able to control that behavior through `Customization > Display Screen > Preferences > Refresh Rate` The default is set to `2 seconds`, you can always increase it for better performance but expect the `display screen` to get slower:

![display_refreash_rate](https://user-images.githubusercontent.com/26286907/84197066-f849c300-aaa9-11ea-9428-4ae3743c09d4.jpg)
