### ISSUE TITLE
Let common tasks be unassigned to an office until someone pulls it

### ISSUE THREAD

**Issue by skymaker-c2is** [mrf345/FQM#159]
I hope the title makes it clear. First of all, thank you for your work and time!

Let's say I want the customers to choose whether they want to speak with a specific person in the office or just anybody in the office. Right now you can do it like this:

1. Create a common task "Doesn't matter".
2. Create tasks for every office with the name of the employee.
The problem with that is (as far as I know): If someone chooses "Doesn't matter", the ticket will be assigned to a random employee. Let's say that employee is in a longer conversation. Another employee is free and he wants to assign the ticket to himself: That's not possible.

The solution would be: Let the tickets be unassigned until an employee assigns/pulls it to himself. So in the "All tickets" view of an operator, there would be really all tickets, whether specific or common tasks, in a chronological order.

Is that possible? If there's already a way to do it, please tell me :)

**Comment by mrf345** [comment]
My pleasure, thanks for the well detailed issue ☺️

As far as i remember tickets that belong to common tasks are assigned to a random office temporary as a user you shouldn't notice it, since they get reassigned whenever pulled. There's a setting that enable and disables this behavior `Strict Tasks Pulling`   https://github.com/mrf345/FQM/pull/61

Although the interface has changed a bit:

![image](https://user-images.githubusercontent.com/26286907/85901838-4fba9380-b80b-11ea-8aaa-15d0543f8715.png)

**Comment by skymaker-c2is** [comment]
Ahhh, sorry. So that's already a feature which I didn't see. Awesome! That makes FQM the perfect software for us.

Thanks for the quick answer!

**Comment by mrf345** [comment]
No worries, happy to help!
