### ISSUE TITLE
Scalability issue

### ISSUE THREAD

**Issue by DaveDavenport** [mrf345/FQM#216]
**Describe the bug**

Not really a bug but also no feature request; but it causes issues. When using this with 20-100+ people, python script uses 100% CPU and response is getting very slow.

Is there a way to improve things? 

**To Reproduce**

Steps to reproduce the issue:
- Setup system
- `python run.py --cli --port 9124 --quiet`
- Use it with 100+ people.

**Please complete the following information:**
 - Operating System (OS):  FreeBSD
 - Browser: A mix. 
 - FQM Version: f9f8851d023e141f64482d53c9ebe4d8c959a36f
 - CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - MEM: 32GB.
 - python 3.7

 - nginx  as a proxy in front of it (providing  ssl);

**Error:**
No log.

If you need more information, please let me know.

**Comment by mrf345** [comment]
This is definitely a limitation that I've discovered while load testing the system for this https://github.com/mrf345/FQM/issues/103 issue. From what I've observed the `Display Screen` seems to be the bottleneck, by default that view emits 2-4 backend requests per second, multiply that with the number of active sessions and that's a recipe for a disaster :)

My initial use-case required a maximum of 4-5 active `Display Screen` sessions each displayed on a separate TV screen. So I've got by that approach just fine. But I'm assuming your use-case requires at least 100-200 `Display Screen` active sessions? If that's the case, then we'll need to do some optimization.

**Things we can do now**:
- Increase the `Refresh Rate` duration from the default `one second` to `five seconds` or maybe more, this will reduce the `Display Screen` number of backend calls per second, as a result, the latency will increase. Follow https://github.com/mrf345/FQM/issues/103#issuecomment-641559353

- Use `gunicorn` server with multiple workers, by default we're using `gevent.pwsgi` server. It's production-ready, However, it's not the fastest out there and it doesn't support workers as far as I know. Workers will allow us to distribute the load onto different processes to take advantage of the CPU multiple cores. However, some event blocking code needs to be refactored first, for it to work. I've opened a separate issue for it https://github.com/mrf345/FQM/issues/217.

- Disable caching and minification, the system tries to cache and minify a lot of stuff to optimize response time, and aesthetics while sacrificing memory and processing power. Unfortunately, there's not an easy way to disable that without changing the code manually. I've opened a separate issue to disable caching and minification if `gunicorn` is detected to be running. https://github.com/mrf345/FQM/issues/218

I think with the changes above in place we'll gain probably a %50+ increase in performance.

**Things we should do in the future**:
- Add a new implementation of `Display Screen` backend and front-end which utilizes `websocket` protocol for realtime communication instead of typical HTTP requests. Most probably we'll use `Flask-Socketio` and `socket.io-Client` for that. This will give us a significant improvement in performance as the numbers of active sessions increase somewhere around %50 improvement for 50-100 requests and %150+ for 500-1000 requests. https://github.com/mrf345/FQM/issues/219

**Comment by mrf345** [comment]
I've just merged a PR https://github.com/mrf345/FQM/pull/220 that let us use `gunicorn`, however, tasks are not supported yet I'll leave it for future implementation.

- Make sure to set a global secret key, example:
```bash
export SECRET_KEY='\x01m\xbbH\x03\xb6.\x87\x9d\xc3\xae96\x0c\x8f\xfc\x8d\xa0\x96^\xe3E\xfc#'
```
- and then run it with `gunicorn -w 6 -b 127.0.0.1:8080 "app"`

Please do let me know if the issue still persists.

**Comment by DaveDavenport** [comment]
I am testing this setup atm. A first test showed a huge improvement (Both in cpu load and user experience).

**Comment by mrf345** [comment]
Awesome, so I'm closing this for now. Hopefully more improvements out of the box in the future with #219

**Comment by DaveDavenport** [comment]
Its been working pretty well, but now threw an error
```
ERROR [flask.app] Exception on /repeat_announcement [GET]                                               │
raceback (most recent call last):                                                                      │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _exe│
ute_context                                                                                            │
   cursor, statement, parameters, context                                                              │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do│
execute                                                                                                │
   cursor.execute(statement, parameters)                                                               │
qlite3.OperationalError: database is locked                                                            │
                                                                                                       │
he above exception was the direct cause of the following exception:                                    │
                                                                                                       │
raceback (most recent call last):                                                                      │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app         │
   response = self.full_dispatch_request()                                                             │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_req│
est                                                                                                    │
   rv = self.handle_user_exception(e)                                                                  │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_excep│
ion                                                                                                    │
   reraise(exc_type, exc_value, tb)                                                                    │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise        │
   raise value                                                                                         │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_req│
est                                                                                                    │
   rv = self.dispatch_request()                                                                        │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request │
   return self.view_functions[rule.endpoint](**req.view_args)                                          │
 File "/home/fqm/FQM/app/views/core.py", line 383, in repeat_announcement                              │
   display_settings = data.Display_store.get()                                                         │
 File "/home/fqm/FQM/app/database.py", line 22, in get                                                 │
   return cls.query.first()                                                                            │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3375, in first │
   ret = list(self[0:1])                                                                               │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3149, in __geti│
em__                                                                                                   │
   return list(res)                                                                                    │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter│
_                                                                                                      │
   return self._execute_and_instances(context)                                                         │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3506, in _execu│
e_and_instances                                                                                        │
   result = conn.execute(querycontext.statement, self._params)                                         │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in exec│
te                                                                                                     │
   return meth(self, multiparams, params)                                                              │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _exe│
ute_on_connection                                                                                      │
   return connection._execute_clauseelement(self, multiparams, params)                                 │
 File "/usr/home/fqm/FQM/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _exe│
ute_clauseelement                                                                                      │
   distilled_params,                                                                                   │
**
```

**Comment by mrf345** [comment]
Sorry about that, I forgot we're using `SQLite3` as DBMS (mixing a file-based DBMS and multiple async workers is a bad idea) we're getting around it with explicitly disabling the same thread check [here](https://github.com/mrf345/FQM/blob/master/app/main.py#L39).

Do you have another DBMS running on the server like MySQL or PostgreSQL? if so, then we can make the SQLite3 optional.

**Comment by DaveDavenport** [comment]
No, it is running in a clean jail, only the needed tools are installed. I could install something (is there a migration path for the data?)

**Comment by mrf345** [comment]
I think we can work around it with increasing the timeout of the database connection, but that's certainly not an ultimate solution.
So probably you'll have to pick MySQL or PostgreSQL. As for data migration between databases, you can use any external tool to do that, `pgloader` for PostgreSQL is a good option with great documentation ([how to migrate SQLite to PostgreSQL](https://pgloader.readthedocs.io/en/latest/ref/sqlite.html)).

In that case, I will be adding a new environment variable for it probably `DATABASE_URI`.

**Comment by mrf345** [comment]
After the PR ☝️is merged, you should set `DATABASE_URI` environment variable, for example:
```bash
export DATABASE_URI='postgresql://username:password@localhost:5432/your_database_name'
```
