### ISSUE TITLE
Python version (3.5)

### ISSUE THREAD

**Issue by bhong2002** [mrf345/FQM#3]
hi sir how do i fix the errors in index.html for python 3.5:
{{ cssify('static/css/main.less') }}
{{ cssify('static/css/spacing.less')}}

thanks :)

**Comment by mrf345** [comment]
Nice work around @bhong2002 , However i chose PySide over PyQT on purpose PySide has more commercial and closed source-code friendly license LGPL. Another thing did you notice a reduction in web server performance when commenting `# monkey.patch_all()` ? Thanks for sharing your work around.

**Comment by mrf345** [comment]
To flask_less issue, can you make sure that `lessc(app=app)` exists in `__init__.py` under `create_app()`. Because it seems the extension is not loaded. If that didn't work, can you try cloning [flask_less](https://github.com/mrf345/flask_less) and running [example.py](https://github.com/mrf345/flask_less/blob/master/example.py) with the same Python 3.6 virtual environment, to make sure the issue is not because of the extension.
