### ISSUE TITLE
Virus Detected by Symantec

### ISSUE THREAD

**Issue by lolotechy** [mrf345/FQM#48]
the executable file is being blocked by Symantec Endpoint Protected for suspecting as a virus.

**Comment by mrf345** [comment]
Thanks for reporting. I'm using `pyinstaller` to generate the `.exe` file for windows. That's a false positive and a known issue as one of the maintainers of `pyinstaller` has mentioned in this issue https://github.com/pyinstaller/pyinstaller/issues/3802#issuecomment-431514817. 
> Please contact your anti-virus vendor. There is nothing we can do about this false positive.


If you're still concerned, as you should. Then you could build your own `.exe` file and examen it. I've went into details on how-to generate a `.exe` file in a previous issue https://github.com/mrf345/FQM/issues/7#issuecomment-444400284.

<hr />

Although after some investigation and comparison i've noticed the anti-viruses that have the false positive have increased since the migration to Python 3. I'm comparing the 0.5 to the 0.6 windows release `.zip` file.

- **0.6 release false positives**: https://www.virustotal.com/gui/file/f71ef1c2624fa5707b8d47b809de45d10ff7bbb409e5f4253a381cbb9b000579/detection
![image](https://user-images.githubusercontent.com/26286907/71886025-87922980-314c-11ea-944e-2d653c92568c.png)

- **0.5 release false positives**: https://www.virustotal.com/gui/file/1687f39b1bf5c39d1a58e1c4acc0d919c2d5740e71ea46038c0ef9d40e52ba32/detection
![image](https://user-images.githubusercontent.com/26286907/71886332-0f783380-314d-11ea-85e8-772464708bbf.png)

So there might be a hope of reducing it by downgrading my  build environment back to an older version of Python 3 or back to Python 2. But most likely that won't be feasible, since the support for Python 2 is soon to be dropped and Python 3.4 is already dropped.

**Comment by mrf345** [comment]
Good news, I managed to reduce the false positives by compiling the `pyinstaller bootloader` locally:

![image](https://user-images.githubusercontent.com/26286907/71904721-b96cb580-3177-11ea-886b-021c2d8a1fd2.png)

I've replaced the old binaries with the new one. However the `.exe` is still unsigned so Windows Defender will still report it as a malicious software. I looked into signing it, but the lowest cost i found is just unreasonable `59$/year` for a free open-source project 😞

**Comment by lolotechy** [comment]
Thanks a lot. 


Best Regards,
Jayvee 
 
  On Tue, 7 Jan 2020 at 11:10 PM, Mohamed Feddad<notifications@github.com> wrote:   
Good news, I managed to reduce the false positives by compiling the pyinstaller bootloader locally:



I've replaced the old binaries with the new one. However the .exe is still unsigned so Windows Defender will still report it as a malicious software. I looked into signing it, but the lowest cost i found is just unreasonable 59$/year for a free open-source project 😞
