### ISSUE TITLE
[Question] [Maybe Issues] - Preassignment of Tickets to an office

### ISSUE THREAD

**Issue by mbbflash** [mrf345/FQM#58]
Hello Mohamed
I would like to ask one question about logic:
I've notice that when a new ticket is created, it is"preassigned" to an office.
This become a problem when there are more office that do the same task, and maybe one office work ""faster"".
I've see that in the last commit you've done i'm able to pull a ticket preassigned to another office, but, in the display screen will continue to call that ticket i've pulled in the office was preassigned to that.

Could be possible to "disable" the preassignment of the office when a task is common to more or to all offices? (es: Ticket A102,B102,c102) 
or, in case this is not possible, could be possible, when the ticket is pulled from an operator, to make the display call and show the office that in fact called the ticket and not the office was preassigned to that?

Thank you so much for reading this and for the answer,

Below there is a GoogleDrive link where you can download a .ZIP with my full FQM Folder (that i've builded myself) 

https://drive.google.com/file/d/1aVCZKIvC8NNg6HNHV9cg--CZ7IMRxqri/view?usp=sharing

Best Regards
Matteo

**Comment by mrf345** [comment]
Hello @mbbflash 

Thanks for letting me know! In my recent commits i was refactoring and adding test coverage for some of the back-end logic responsible for handling tasks and offices in `manage` blueprint endpoints, while the back-end logic for pulling and rearrange tickets queues weren't refactored. I've forgot that part of the code `core` blueprint isn't test-covered yet, so most probably one of the recent merged commits has introduced that bug. No worries though, i'm moving next to refactoring that part.

To your question regarding offices and tasks logic. Initially Offices to Tasks relationship used to be parent to child `one to many` in terms of database structure. However after introducing common tasks sometime ago, that relationship had to change to `many to many`, so major database structure and back-end refactoring was needed. That's why you might notice offices and tasks are used interchangeably.

With that been said, offices are still needed as containers for non-common tasks. Same apply for common tasks but to a lesser extent. Most of the current code-base relays heavily on it and future features will. `Multiple Display screen support based on offices` a feature that i will be implementing for the upcoming release for example.

I had another approach to resolving the issue, i was planning to add a new flag setting to enable or disable strict pulling across offices for common tasks. Additionally to fixing the bug that got recently introduced. I will be pushing a PR to resolve it soon.

Hope that explains, please let me know if you think of a better approach to tackle it.

All the best!

**Comment by mrf345** [comment]
@mbbflash I'm about to merge a PR that should resolves the issue, and adds the strict pulling setting. Checkout the description for a quick how-to https://github.com/mrf345/FQM/pull/61#issue-371490241 Please let me know if the issue still persists.
